version: '3.8'

services:
  plaster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "35200:3000"  # Bind container's port 3000 to the host's port 3000
    restart: always
    container_name: plaster
