services:
  plaster:
    image: docker.io/library/plasterbin:latest
    container_name: plaster
    ports:
      - "35200:3000"  #modify first port if needed
    restart: always
    networks:
      - plaster-network

    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900 --include-restarting
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
networks:
  plaster-network:
    driver: bridge
