services:
  plaster:
    image: docker.io/library/plasterbin:latest
    container_name: plaster
    ports:
      - "35200:3000"  #modify first port if needed
    restart: always
    networks:
      - plaster-network
networks:
  plaster-network:
    driver: bridge
