version: '3.8'

services:
  plaster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "35200:3000"  # change host port if needed
    restart: always
    container_name: plaster
