version: '3.8'

services:
  plaster:
    image: ghcr.io/gigirassy/plaster
    ports:
      - "35200:3000"  # change host port if needed
    environment:
      AUTO_COPY_DEFAULT: "false" # if enabled, this will automatically copy paste contents to the clipboard on main page
    restart: always
    container_name: plaster
